package tui

import (
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/muesli/termenv"
)

// The approved front-facing Gopher, sampled directly from original-pixel.png.
// Regenerate with assets/gopher/rasterize.go; no hand-redrawn features or props.
// Two vertical pixels share a Unicode half-block cell; no image protocol.
const gopherPixels = `........................................
..............bbbbbbbbbbbb..............
............bbbbbbbbbbbbbbbbb...........
..........bbbbbbbbbbbbbbdddbbb...bb.....
....bbb.bbdsllldbbbbbbdlwwwldbbbbbbb....
...bbbbdbdlwwwwwlbbbbdwwwwwwwdbbdodbb...
..bbdodbdlwwwwwwwdbbdlwwwwwwwlbbboobb...
..bboobbslslwwwwwlbbdloowwwwwwdbbddbb...
..bbbdbblsoolwwwwldbdsosswwwwwdbbbdbb...
...bdbbblsoslwwwwldbdloslwwwwwdbbbdb....
.....bbbdwslwwwwwsbbblllwwwwwlbbbbb.....
.....bbbblwwwwwwwdbdddwwwwwwwdbbbbb.....
....bbbbbbllwwwldbooosddlllsdbbbbbb.....
....bbbbbbbddddbbsooossbbbbbbbbbbbb.....
....bbbbbbbbbbbbtppttppsbbbbbbbbbbb.....
....bbbbbbbbbbbbtptttlpsbbbbbbbbbbbb....
....bbbbbbbbbbbbbslswldbbbbbbbbbbbbb....
....bbbbbbbbbbbbbswswlbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbdwswlbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbdbdbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
..ppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppp.
.tppbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbppl.
.pp.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.pp.
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....
.....bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.....
......bbbbbbbbbbbbbbbbbbbbbbbbbbbb......
......bbbbbbbbbbbbbbbbbbbbbbbbbbbb......
.......bbbbbbbbbbbbbbbbbbbbbbbbbb.......
........bbbbbbbbbbbbbbbbbbbbbbbb........
.......psbbbbbbbbbbbbbbbbbbbbbbppp......
......pppl.bbbbbbbbbbbbbbbbbb.pppp......
.....ptpp.....bbbbbbbbbbbb.....ppt......
......pp........................p.......
........................................`

const gopherWidth = 40

// A separately sampled copy for ordinary 80×24 terminals. Both sizes come
// directly from the same approved image, not from scaling the character grid.
const gopherCompactWidth = 26
const gopherCompactPixels = `..........................
.........bbbbbbbb.........
.......bbbbbbbbbbbb.......
..bbbbblllbbbbbwwllbbbb...
..bddblwwwwbbbwwwwwbbodb..
..bsbbsswwwlbloswwwlbbbb..
..bdbbsswwwlbloswwwlbbd...
...bbbllwwwbbdlwwwwbbb....
...bbbblwlldoodlllbbbbb...
...bbbbbbbbtsstbbbbbbbb...
...bbbbbbbdpttpbbbbbbbb...
...bbbbbbbbslwdbbbbbbbb...
...bbbbbbbblllbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
.ppbbbbbbbbbbbbbbbbbbbbpp.
.ppbbbbbbbbbbbbbbbbbbbb.p.
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbbb..
...bbbbbbbbbbbbbbbbbbbbb..
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
...bbbbbbbbbbbbbbbbbbbb...
....bbbbbbbbbbbbbbbbbb....
....bbbbbbbbbbbbbbbbbb....
.....bbbbbbbbbbbbbbbb.....
.....lbbbbbbbbbbbbbbl.....
....ppl.bbbbbbbbbb.ppp....
....pp..............pp....
..........................`

var gopherPalette = map[byte]lipgloss.Color{
	'o': "#000000", // pupils, nose and interior outlines
	'b': "#67D2DF", // original cyan body
	'w': "#FFFFFF", // eyes and two teeth
	'p': "#F6D3A3", // muzzle and tiny paws
	'd': "#33696F", // sampled cyan edge
	's': "#555555", // sampled dark eye/teeth edge
	'l': "#BEBEBE", // sampled light eye/teeth edge
	't': "#968163", // sampled tan edge
	'h': "#A7E4EB", // sampled cyan/white edge
}

func renderGopher() string {
	return renderGopherPixels(gopherPixels, gopherWidth)
}

func renderGopherPixels(pixels string, width int) string {
	rows := strings.Split(pixels, "\n")
	var out strings.Builder
	monochrome := lipgloss.ColorProfile() == termenv.Ascii
	for y := 0; y < len(rows); y += 2 {
		if y > 0 {
			out.WriteByte('\n')
		}
		for x := 0; x < width; x++ {
			top, bottom := rows[y][x], rows[y+1][x]
			if monochrome {
				out.WriteString(gopherMonoCell(top, bottom))
				continue
			}
			style := lipgloss.NewStyle()
			switch {
			case top == '.' && bottom == '.':
				out.WriteByte(' ')
			case top == '.':
				out.WriteString(style.Foreground(gopherPalette[bottom]).Render("▄"))
			case bottom == '.':
				out.WriteString(style.Foreground(gopherPalette[top]).Render("▀"))
			default:
				out.WriteString(style.Foreground(gopherPalette[top]).Background(gopherPalette[bottom]).Render("▀"))
			}
		}
	}
	return out.String()
}

// Keep eyes and pupils distinguishable with NO_COLOR too.
// A solid silhouette would lose the face when ANSI colors are unavailable.
func gopherMonoCell(top, bottom byte) string {
	bright := func(p byte) bool { return p == 'w' }
	switch {
	case top == '.' && bottom == '.':
		return " "
	case bright(top) && bright(bottom):
		return "█"
	case bright(top):
		return "▀"
	case bright(bottom):
		return "▄"
	case top == 'o' || bottom == 'o':
		return " "
	case top == '.' || bottom == '.':
		return "░"
	default:
		return "▒"
	}
}
